### ISSUE TITLE
CSS优化建议

### ISSUE THREAD

**Issue by dream2023** [yansenlei/VJsoneditor#5]
我们一般在写第三方组件时，css都不加scoped，原因是需要方便人修改，如果加上scoped后，权重就超过单独的类，所以一般是要去掉scoped：

![image](https://user-images.githubusercontent.com/19297757/62096569-abf0fc80-b2b6-11e9-9f66-14fc029a8729.png)

例如： 我需要修改一下代码：
```css
.jsoneditor-container.min-box {
  min-width: auto;
}
```

以上是无法修改成功的

需要
```css
.jsoneditor-container.min-box {
  min-width: auto !important;
}
```
或者再加一个父类
